# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created: Wed Dec 30 12:41:16 2015
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(891, 680)
        self.gridLayout_4 = QtWidgets.QGridLayout(Form)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(300, -1, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.start_btn = QtWidgets.QPushButton(Form)
        self.start_btn.setObjectName("start_btn")
        self.verticalLayout.addWidget(self.start_btn)
        self.stop_btn = QtWidgets.QPushButton(Form)
        self.stop_btn.setObjectName("stop_btn")
        self.verticalLayout.addWidget(self.stop_btn)
        self.throttle_sendOnChange_bool = QtWidgets.QCheckBox(Form)
        self.throttle_sendOnChange_bool.setObjectName("throttle_sendOnChange_bool")
        self.verticalLayout.addWidget(self.throttle_sendOnChange_bool)
        self.angles_sendOnChange_bool = QtWidgets.QCheckBox(Form)
        self.angles_sendOnChange_bool.setObjectName("angles_sendOnChange_bool")
        self.verticalLayout.addWidget(self.angles_sendOnChange_bool)
        self.use_gamepad_bool = QtWidgets.QCheckBox(Form)
        self.use_gamepad_bool.setObjectName("use_gamepad_bool")
        self.verticalLayout.addWidget(self.use_gamepad_bool)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.data_label = QtWidgets.QLabel(Form)
        self.data_label.setObjectName("data_label")
        self.verticalLayout.addWidget(self.data_label)
        self.packet_label = QtWidgets.QLabel(Form)
        self.packet_label.setObjectName("packet_label")
        self.verticalLayout.addWidget(self.packet_label)
        self.gridLayout_4.addLayout(self.verticalLayout, 3, 1, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.roll_label = QtWidgets.QLabel(Form)
        self.roll_label.setObjectName("roll_label")
        self.gridLayout.addWidget(self.roll_label, 4, 0, 1, 1)
        self.angles_roll_slider = QtWidgets.QSlider(Form)
        self.angles_roll_slider.setMouseTracking(False)
        self.angles_roll_slider.setMinimum(-100)
        self.angles_roll_slider.setMaximum(100)
        self.angles_roll_slider.setOrientation(QtCore.Qt.Horizontal)
        self.angles_roll_slider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.angles_roll_slider.setTickInterval(10)
        self.angles_roll_slider.setObjectName("angles_roll_slider")
        self.gridLayout.addWidget(self.angles_roll_slider, 5, 0, 1, 1)
        self.pitch_label = QtWidgets.QLabel(Form)
        self.pitch_label.setObjectName("pitch_label")
        self.gridLayout.addWidget(self.pitch_label, 2, 0, 1, 1)
        self.angles_pitch_slider = QtWidgets.QSlider(Form)
        self.angles_pitch_slider.setMinimum(-100)
        self.angles_pitch_slider.setMaximum(100)
        self.angles_pitch_slider.setOrientation(QtCore.Qt.Horizontal)
        self.angles_pitch_slider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.angles_pitch_slider.setTickInterval(10)
        self.angles_pitch_slider.setObjectName("angles_pitch_slider")
        self.gridLayout.addWidget(self.angles_pitch_slider, 3, 0, 1, 1)
        self.angles_yaw_slider = QtWidgets.QSlider(Form)
        self.angles_yaw_slider.setMinimum(-100)
        self.angles_yaw_slider.setMaximum(100)
        self.angles_yaw_slider.setOrientation(QtCore.Qt.Horizontal)
        self.angles_yaw_slider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.angles_yaw_slider.setTickInterval(10)
        self.angles_yaw_slider.setObjectName("angles_yaw_slider")
        self.gridLayout.addWidget(self.angles_yaw_slider, 1, 0, 1, 1)
        self.yaw_label = QtWidgets.QLabel(Form)
        self.yaw_label.setObjectName("yaw_label")
        self.gridLayout.addWidget(self.yaw_label, 0, 0, 1, 1)
        self.angles_yaw_doubleSpinBox = QtWidgets.QDoubleSpinBox(Form)
        self.angles_yaw_doubleSpinBox.setObjectName("angles_yaw_doubleSpinBox")
        self.gridLayout.addWidget(self.angles_yaw_doubleSpinBox, 1, 1, 1, 1)
        self.angles_pitch_doubleSpinBox = QtWidgets.QDoubleSpinBox(Form)
        self.angles_pitch_doubleSpinBox.setObjectName("angles_pitch_doubleSpinBox")
        self.gridLayout.addWidget(self.angles_pitch_doubleSpinBox, 3, 1, 1, 1)
        self.angles_roll_doubleSpinBox = QtWidgets.QDoubleSpinBox(Form)
        self.angles_roll_doubleSpinBox.setObjectName("angles_roll_doubleSpinBox")
        self.gridLayout.addWidget(self.angles_roll_doubleSpinBox, 4, 1, 2, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.roll_max_spinbox = QtWidgets.QSpinBox(Form)
        self.roll_max_spinbox.setMinimum(-100)
        self.roll_max_spinbox.setMaximum(100)
        self.roll_max_spinbox.setProperty("value", 30)
        self.roll_max_spinbox.setObjectName("roll_max_spinbox")
        self.gridLayout_3.addWidget(self.roll_max_spinbox, 4, 1, 2, 1)
        self.roll_label_2 = QtWidgets.QLabel(Form)
        self.roll_label_2.setObjectName("roll_label_2")
        self.gridLayout_3.addWidget(self.roll_label_2, 4, 0, 1, 1)
        self.pitch_max_slider = QtWidgets.QSlider(Form)
        self.pitch_max_slider.setMinimum(0)
        self.pitch_max_slider.setMaximum(100)
        self.pitch_max_slider.setProperty("value", 30)
        self.pitch_max_slider.setOrientation(QtCore.Qt.Horizontal)
        self.pitch_max_slider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.pitch_max_slider.setTickInterval(10)
        self.pitch_max_slider.setObjectName("pitch_max_slider")
        self.gridLayout_3.addWidget(self.pitch_max_slider, 3, 0, 1, 1)
        self.yaw_label_2 = QtWidgets.QLabel(Form)
        self.yaw_label_2.setObjectName("yaw_label_2")
        self.gridLayout_3.addWidget(self.yaw_label_2, 0, 0, 1, 1)
        self.roll_max_slider = QtWidgets.QSlider(Form)
        self.roll_max_slider.setMouseTracking(False)
        self.roll_max_slider.setMinimum(0)
        self.roll_max_slider.setMaximum(100)
        self.roll_max_slider.setProperty("value", 30)
        self.roll_max_slider.setOrientation(QtCore.Qt.Horizontal)
        self.roll_max_slider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.roll_max_slider.setTickInterval(10)
        self.roll_max_slider.setObjectName("roll_max_slider")
        self.gridLayout_3.addWidget(self.roll_max_slider, 5, 0, 1, 1)
        self.yaw_max_spinbox = QtWidgets.QSpinBox(Form)
        self.yaw_max_spinbox.setMinimum(0)
        self.yaw_max_spinbox.setMaximum(100)
        self.yaw_max_spinbox.setProperty("value", 30)
        self.yaw_max_spinbox.setObjectName("yaw_max_spinbox")
        self.gridLayout_3.addWidget(self.yaw_max_spinbox, 1, 1, 1, 1)
        self.pitch_max_spinbox = QtWidgets.QSpinBox(Form)
        self.pitch_max_spinbox.setMinimum(-100)
        self.pitch_max_spinbox.setMaximum(100)
        self.pitch_max_spinbox.setProperty("value", 30)
        self.pitch_max_spinbox.setObjectName("pitch_max_spinbox")
        self.gridLayout_3.addWidget(self.pitch_max_spinbox, 3, 1, 1, 1)
        self.yaw_max_slider = QtWidgets.QSlider(Form)
        self.yaw_max_slider.setMinimum(0)
        self.yaw_max_slider.setMaximum(100)
        self.yaw_max_slider.setProperty("value", 30)
        self.yaw_max_slider.setOrientation(QtCore.Qt.Horizontal)
        self.yaw_max_slider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.yaw_max_slider.setTickInterval(10)
        self.yaw_max_slider.setObjectName("yaw_max_slider")
        self.gridLayout_3.addWidget(self.yaw_max_slider, 1, 0, 1, 1)
        self.pitch_label_2 = QtWidgets.QLabel(Form)
        self.pitch_label_2.setObjectName("pitch_label_2")
        self.gridLayout_3.addWidget(self.pitch_label_2, 2, 0, 1, 1)
        self.throttle_max_spinBox = QtWidgets.QSpinBox(Form)
        self.throttle_max_spinBox.setMaximum(2000)
        self.throttle_max_spinBox.setProperty("value", 500)
        self.throttle_max_spinBox.setObjectName("throttle_max_spinBox")
        self.gridLayout_3.addWidget(self.throttle_max_spinBox, 6, 1, 1, 1)
        self.gamepad_frequency_spinBox = QtWidgets.QSpinBox(Form)
        self.gamepad_frequency_spinBox.setMinimum(1)
        self.gamepad_frequency_spinBox.setMaximum(100)
        self.gamepad_frequency_spinBox.setProperty("value", 10)
        self.gamepad_frequency_spinBox.setObjectName("gamepad_frequency_spinBox")
        self.gridLayout_3.addWidget(self.gamepad_frequency_spinBox, 7, 1, 1, 1)
        self.max_apply = QtWidgets.QPushButton(Form)
        self.max_apply.setObjectName("max_apply")
        self.gridLayout_3.addWidget(self.max_apply, 8, 0, 1, 1)
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 6, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 7, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 9, 0, 1, 1)
        self.PID_p = QtWidgets.QDoubleSpinBox(Form)
        self.PID_p.setMaximum(5.0)
        self.PID_p.setSingleStep(0.01)
        self.PID_p.setProperty("value", 0.7)
        self.PID_p.setObjectName("PID_p")
        self.gridLayout_3.addWidget(self.PID_p, 10, 0, 1, 1)
        self.send_PID = QtWidgets.QPushButton(Form)
        self.send_PID.setObjectName("send_PID")
        self.gridLayout_3.addWidget(self.send_PID, 11, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 1, 2, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.angles_reset_btn = QtWidgets.QPushButton(Form)
        self.angles_reset_btn.setObjectName("angles_reset_btn")
        self.verticalLayout_2.addWidget(self.angles_reset_btn)
        self.angles_send_btn = QtWidgets.QPushButton(Form)
        self.angles_send_btn.setObjectName("angles_send_btn")
        self.verticalLayout_2.addWidget(self.angles_send_btn)
        self.gridLayout_4.addLayout(self.verticalLayout_2, 1, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.throttle_spinBox = QtWidgets.QSpinBox(Form)
        self.throttle_spinBox.setMaximum(1000)
        self.throttle_spinBox.setObjectName("throttle_spinBox")
        self.gridLayout_2.addWidget(self.throttle_spinBox, 2, 1, 1, 1)
        self.throttle_slider = QtWidgets.QSlider(Form)
        self.throttle_slider.setMaximum(1000)
        self.throttle_slider.setSingleStep(10)
        self.throttle_slider.setPageStep(100)
        self.throttle_slider.setOrientation(QtCore.Qt.Vertical)
        self.throttle_slider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.throttle_slider.setTickInterval(10)
        self.throttle_slider.setObjectName("throttle_slider")
        self.gridLayout_2.addWidget(self.throttle_slider, 0, 0, 1, 1)
        self.throttle_send_btn = QtWidgets.QPushButton(Form)
        self.throttle_send_btn.setObjectName("throttle_send_btn")
        self.gridLayout_2.addWidget(self.throttle_send_btn, 1, 1, 1, 1)
        self.throttle_label = QtWidgets.QLabel(Form)
        self.throttle_label.setObjectName("throttle_label")
        self.gridLayout_2.addWidget(self.throttle_label, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 2, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 3, 0, 1, 1)

        self.retranslateUi(Form)
        self.throttle_slider.valueChanged['int'].connect(self.throttle_spinBox.setValue)
        self.throttle_spinBox.valueChanged['int'].connect(self.throttle_slider.setValue)
        self.yaw_max_slider.valueChanged['int'].connect(self.yaw_max_spinbox.setValue)
        self.pitch_max_slider.valueChanged['int'].connect(self.pitch_max_spinbox.setValue)
        self.roll_max_slider.valueChanged['int'].connect(self.roll_max_spinbox.setValue)
        self.yaw_max_spinbox.valueChanged['int'].connect(self.yaw_max_slider.setValue)
        self.pitch_max_spinbox.valueChanged['int'].connect(self.pitch_max_slider.setValue)
        self.roll_max_spinbox.valueChanged['int'].connect(self.roll_max_slider.setValue)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.start_btn.setText(_translate("Form", "Start engines"))
        self.stop_btn.setText(_translate("Form", "Stop engines"))
        self.throttle_sendOnChange_bool.setText(_translate("Form", "Send throttle on change"))
        self.angles_sendOnChange_bool.setText(_translate("Form", "Send angles  on change"))
        self.use_gamepad_bool.setText(_translate("Form", "Use gamepad"))
        self.data_label.setText(_translate("Form", "Bytes sent:"))
        self.packet_label.setText(_translate("Form", "Packets sent:"))
        self.roll_label.setText(_translate("Form", "Roll"))
        self.pitch_label.setText(_translate("Form", "Pitch"))
        self.yaw_label.setText(_translate("Form", "Yaw"))
        self.roll_label_2.setText(_translate("Form", "Max roll"))
        self.yaw_label_2.setText(_translate("Form", "Max yaw"))
        self.pitch_label_2.setText(_translate("Form", "Max pitch"))
        self.max_apply.setText(_translate("Form", "Apply changes"))
        self.label.setText(_translate("Form", "Max throttle"))
        self.label_2.setText(_translate("Form", "Gamepad update frequency (gyro is 100 Hz)"))
        self.label_3.setText(_translate("Form", "Pitch/Rol PIDl p-value"))
        self.send_PID.setText(_translate("Form", "Send PID values"))
        self.angles_reset_btn.setText(_translate("Form", "Reset angles"))
        self.angles_send_btn.setText(_translate("Form", "Send angles"))
        self.throttle_send_btn.setText(_translate("Form", "Send throttle"))
        self.throttle_label.setText(_translate("Form", "Throttle"))

