# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(671, 454)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(250, 20, 272, 251))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.yaw_label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.yaw_label_2.setObjectName("yaw_label_2")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.yaw_label_2)
        self.yaw_max_spinbox = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        self.yaw_max_spinbox.setMinimum(0)
        self.yaw_max_spinbox.setMaximum(1000)
        self.yaw_max_spinbox.setProperty("value", 20)
        self.yaw_max_spinbox.setObjectName("yaw_max_spinbox")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.yaw_max_spinbox)
        self.pitch_label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.pitch_label_2.setObjectName("pitch_label_2")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.pitch_label_2)
        self.pitch_max_spinbox = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        self.pitch_max_spinbox.setMinimum(0)
        self.pitch_max_spinbox.setMaximum(1000)
        self.pitch_max_spinbox.setProperty("value", 20)
        self.pitch_max_spinbox.setObjectName("pitch_max_spinbox")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.pitch_max_spinbox)
        self.roll_label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.roll_label_2.setObjectName("roll_label_2")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.roll_label_2)
        self.roll_max_spinbox = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        self.roll_max_spinbox.setMinimum(0)
        self.roll_max_spinbox.setMaximum(1000)
        self.roll_max_spinbox.setProperty("value", 20)
        self.roll_max_spinbox.setObjectName("roll_max_spinbox")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.roll_max_spinbox)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label.setObjectName("label")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label)
        self.throttle_max_spinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        self.throttle_max_spinBox.setMaximum(2000)
        self.throttle_max_spinBox.setProperty("value", 300)
        self.throttle_max_spinBox.setObjectName("throttle_max_spinBox")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.throttle_max_spinBox)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.gamepad_frequency_spinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        self.gamepad_frequency_spinBox.setMinimum(1)
        self.gamepad_frequency_spinBox.setMaximum(100)
        self.gamepad_frequency_spinBox.setProperty("value", 10)
        self.gamepad_frequency_spinBox.setObjectName("gamepad_frequency_spinBox")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.gamepad_frequency_spinBox)
        self.verticalLayout_2.addLayout(self.formLayout_3)
        self.throttle_sendOnChange_bool = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.throttle_sendOnChange_bool.setObjectName("throttle_sendOnChange_bool")
        self.verticalLayout_2.addWidget(self.throttle_sendOnChange_bool)
        self.angles_sendOnChange_bool = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.angles_sendOnChange_bool.setObjectName("angles_sendOnChange_bool")
        self.verticalLayout_2.addWidget(self.angles_sendOnChange_bool)
        self.gamepad_connect_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.gamepad_connect_btn.setCheckable(True)
        self.gamepad_connect_btn.setChecked(False)
        self.gamepad_connect_btn.setObjectName("gamepad_connect_btn")
        self.verticalLayout_2.addWidget(self.gamepad_connect_btn)
        self.gamepad_apply_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.gamepad_apply_btn.setObjectName("gamepad_apply_btn")
        self.verticalLayout_2.addWidget(self.gamepad_apply_btn)
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(230, 20, 20, 401))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(520, 20, 20, 401))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(Form)
        self.line_3.setGeometry(QtCore.QRect(30, 270, 501, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 20, 200, 401))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.angles_reset_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.angles_reset_btn.setObjectName("angles_reset_btn")
        self.gridLayout.addWidget(self.angles_reset_btn, 7, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 2, 1, 1)
        self.pitch_offset_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.pitch_offset_doubleSpinBox.setMinimum(-500.0)
        self.pitch_offset_doubleSpinBox.setMaximum(500.0)
        self.pitch_offset_doubleSpinBox.setObjectName("pitch_offset_doubleSpinBox")
        self.gridLayout.addWidget(self.pitch_offset_doubleSpinBox, 4, 2, 1, 1)
        self.roll_offset_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.roll_offset_doubleSpinBox.setMinimum(-500.0)
        self.roll_offset_doubleSpinBox.setMaximum(500.0)
        self.roll_offset_doubleSpinBox.setObjectName("roll_offset_doubleSpinBox")
        self.gridLayout.addWidget(self.roll_offset_doubleSpinBox, 5, 2, 1, 1)
        self.yaw_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.yaw_doubleSpinBox.setMinimum(-500.0)
        self.yaw_doubleSpinBox.setMaximum(500.0)
        self.yaw_doubleSpinBox.setObjectName("yaw_doubleSpinBox")
        self.gridLayout.addWidget(self.yaw_doubleSpinBox, 1, 1, 1, 1)
        self.angles_send_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.angles_send_btn.setObjectName("angles_send_btn")
        self.gridLayout.addWidget(self.angles_send_btn, 7, 0, 1, 2)
        self.yaw_label = QtWidgets.QLabel(self.layoutWidget)
        self.yaw_label.setObjectName("yaw_label")
        self.gridLayout.addWidget(self.yaw_label, 1, 0, 1, 1)
        self.pitch_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.pitch_doubleSpinBox.setMinimum(-500.0)
        self.pitch_doubleSpinBox.setMaximum(500.0)
        self.pitch_doubleSpinBox.setObjectName("pitch_doubleSpinBox")
        self.gridLayout.addWidget(self.pitch_doubleSpinBox, 4, 1, 1, 1)
        self.roll_label = QtWidgets.QLabel(self.layoutWidget)
        self.roll_label.setObjectName("roll_label")
        self.gridLayout.addWidget(self.roll_label, 5, 0, 1, 1)
        self.pitch_label = QtWidgets.QLabel(self.layoutWidget)
        self.pitch_label.setObjectName("pitch_label")
        self.gridLayout.addWidget(self.pitch_label, 4, 0, 1, 1)
        self.roll_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.roll_doubleSpinBox.setMinimum(-500.0)
        self.roll_doubleSpinBox.setMaximum(500.0)
        self.roll_doubleSpinBox.setObjectName("roll_doubleSpinBox")
        self.gridLayout.addWidget(self.roll_doubleSpinBox, 5, 1, 1, 1)
        self.yaw_offset_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.yaw_offset_doubleSpinBox.setMinimum(-500.0)
        self.yaw_offset_doubleSpinBox.setMaximum(500.0)
        self.yaw_offset_doubleSpinBox.setObjectName("yaw_offset_doubleSpinBox")
        self.gridLayout.addWidget(self.yaw_offset_doubleSpinBox, 1, 2, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.throttle_label = QtWidgets.QLabel(self.layoutWidget)
        self.throttle_label.setObjectName("throttle_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.throttle_label)
        self.throttle_spinBox = QtWidgets.QSpinBox(self.layoutWidget)
        self.throttle_spinBox.setMaximum(2000)
        self.throttle_spinBox.setObjectName("throttle_spinBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.throttle_spinBox)
        self.throttle_label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.throttle_label_3.setObjectName("throttle_label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.throttle_label_3)
        self.throttle_offset_spinBox = QtWidgets.QSpinBox(self.layoutWidget)
        self.throttle_offset_spinBox.setMaximum(2000)
        self.throttle_offset_spinBox.setSingleStep(10)
        self.throttle_offset_spinBox.setProperty("value", 0)
        self.throttle_offset_spinBox.setObjectName("throttle_offset_spinBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.throttle_offset_spinBox)
        self.throttle_label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.throttle_label_2.setObjectName("throttle_label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.throttle_label_2)
        self.throttle_offset_step_spinBox = QtWidgets.QSpinBox(self.layoutWidget)
        self.throttle_offset_step_spinBox.setMaximum(1000)
        self.throttle_offset_step_spinBox.setSingleStep(10)
        self.throttle_offset_step_spinBox.setProperty("value", 50)
        self.throttle_offset_step_spinBox.setObjectName("throttle_offset_step_spinBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.throttle_offset_step_spinBox)
        self.throttle_send_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.throttle_send_btn.setObjectName("throttle_send_btn")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.throttle_send_btn)
        self.throttle_reset_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.throttle_reset_btn.setObjectName("throttle_reset_btn")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.throttle_reset_btn)
        self.verticalLayout_4.addLayout(self.formLayout)
        self.layoutWidget1 = QtWidgets.QWidget(Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(260, 280, 140, 143))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.pid_rollpitch_p = QtWidgets.QDoubleSpinBox(self.layoutWidget1)
        self.pid_rollpitch_p.setMaximum(5.0)
        self.pid_rollpitch_p.setSingleStep(0.01)
        self.pid_rollpitch_p.setProperty("value", 0.7)
        self.pid_rollpitch_p.setObjectName("pid_rollpitch_p")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.pid_rollpitch_p)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.pid_rollpitch_i = QtWidgets.QDoubleSpinBox(self.layoutWidget1)
        self.pid_rollpitch_i.setMaximum(5.0)
        self.pid_rollpitch_i.setSingleStep(0.01)
        self.pid_rollpitch_i.setProperty("value", 0.0)
        self.pid_rollpitch_i.setObjectName("pid_rollpitch_i")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.pid_rollpitch_i)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.pid_yaw_p = QtWidgets.QDoubleSpinBox(self.layoutWidget1)
        self.pid_yaw_p.setMaximum(5.0)
        self.pid_yaw_p.setSingleStep(0.01)
        self.pid_yaw_p.setProperty("value", 0.7)
        self.pid_yaw_p.setObjectName("pid_yaw_p")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.pid_yaw_p)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.verticalLayout.addLayout(self.formLayout_2)
        self.pid_send_btn = QtWidgets.QPushButton(self.layoutWidget1)
        self.pid_send_btn.setObjectName("pid_send_btn")
        self.verticalLayout.addWidget(self.pid_send_btn)
        self.layoutWidget2 = QtWidgets.QWidget(Form)
        self.layoutWidget2.setGeometry(QtCore.QRect(550, 220, 119, 201))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.serial_open_btn = QtWidgets.QPushButton(self.layoutWidget2)
        self.serial_open_btn.setObjectName("serial_open_btn")
        self.verticalLayout_3.addWidget(self.serial_open_btn)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.start_btn = QtWidgets.QPushButton(self.layoutWidget2)
        self.start_btn.setObjectName("start_btn")
        self.verticalLayout_3.addWidget(self.start_btn)
        self.stop_btn = QtWidgets.QPushButton(self.layoutWidget2)
        self.stop_btn.setObjectName("stop_btn")
        self.verticalLayout_3.addWidget(self.stop_btn)
        self.yaw_reset_btn = QtWidgets.QPushButton(self.layoutWidget2)
        self.yaw_reset_btn.setObjectName("yaw_reset_btn")
        self.verticalLayout_3.addWidget(self.yaw_reset_btn)
        self.data_label = QtWidgets.QLabel(self.layoutWidget2)
        self.data_label.setObjectName("data_label")
        self.verticalLayout_3.addWidget(self.data_label)
        self.packet_label = QtWidgets.QLabel(self.layoutWidget2)
        self.packet_label.setObjectName("packet_label")
        self.verticalLayout_3.addWidget(self.packet_label)
        self.layoutWidget3 = QtWidgets.QWidget(Form)
        self.layoutWidget3.setGeometry(QtCore.QRect(531, 70, 131, 83))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.mode_raw_btn = QtWidgets.QPushButton(self.layoutWidget3)
        self.mode_raw_btn.setObjectName("mode_raw_btn")
        self.verticalLayout_5.addWidget(self.mode_raw_btn)
        self.mode_angle_btn = QtWidgets.QPushButton(self.layoutWidget3)
        self.mode_angle_btn.setObjectName("mode_angle_btn")
        self.verticalLayout_5.addWidget(self.mode_angle_btn)
        self.mode_rate_btn = QtWidgets.QPushButton(self.layoutWidget3)
        self.mode_rate_btn.setObjectName("mode_rate_btn")
        self.verticalLayout_5.addWidget(self.mode_rate_btn)
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.verticalLayoutWidget_2.raise_()
        self.line.raise_()
        self.line_2.raise_()
        self.line_3.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Quadcopter controller"))
        self.label_8.setText(_translate("Form", "Gamepad"))
        self.yaw_label_2.setText(_translate("Form", "Max yaw"))
        self.pitch_label_2.setText(_translate("Form", "Max pitch"))
        self.roll_label_2.setText(_translate("Form", "Max roll"))
        self.label.setText(_translate("Form", "Max throttle"))
        self.label_2.setText(_translate("Form", "Gamepad update frequency (gyro is 100 Hz)"))
        self.throttle_sendOnChange_bool.setText(_translate("Form", "Send throttle"))
        self.angles_sendOnChange_bool.setText(_translate("Form", "Send angles"))
        self.gamepad_connect_btn.setText(_translate("Form", "Connect gamepad"))
        self.gamepad_apply_btn.setText(_translate("Form", "Change frequency"))
        self.angles_reset_btn.setText(_translate("Form", "Reset angles"))
        self.label_9.setText(_translate("Form", "Angles"))
        self.label_10.setText(_translate("Form", "Offsets"))
        self.angles_send_btn.setText(_translate("Form", "Send angles"))
        self.yaw_label.setText(_translate("Form", "Yaw"))
        self.roll_label.setText(_translate("Form", "Roll"))
        self.pitch_label.setText(_translate("Form", "Pitch"))
        self.throttle_label.setText(_translate("Form", "Throttle"))
        self.throttle_label_3.setText(_translate("Form", "Throttle offset"))
        self.throttle_label_2.setText(_translate("Form", "Throttle offset step size"))
        self.throttle_send_btn.setText(_translate("Form", "Send throttle"))
        self.throttle_reset_btn.setText(_translate("Form", "Reset thr"))
        self.label_5.setText(_translate("Form", "PID Settings"))
        self.label_3.setText(_translate("Form", "Roll/Pitch p-value"))
        self.label_4.setText(_translate("Form", "Roll/Pitch i-value"))
        self.label_6.setText(_translate("Form", "Yaw p-value"))
        self.label_7.setText(_translate("Form", "Yaw i-value"))
        self.pid_send_btn.setText(_translate("Form", "Send PID values"))
        self.serial_open_btn.setText(_translate("Form", "Open serial connection"))
        self.start_btn.setText(_translate("Form", "Start engines"))
        self.stop_btn.setText(_translate("Form", "Stop engines"))
        self.yaw_reset_btn.setText(_translate("Form", "Reset yaw"))
        self.data_label.setText(_translate("Form", "Bytes sent:"))
        self.packet_label.setText(_translate("Form", "Packets sent:"))
        self.mode_raw_btn.setText(_translate("Form", "Raw control mode"))
        self.mode_angle_btn.setText(_translate("Form", "Angle control mode"))
        self.mode_rate_btn.setText(_translate("Form", "Rate control mode"))

